AST_NODES =  \
  src/ast/array-exp.hh src/ast/array-exp.hxx src/ast/array-exp.cc \
  src/ast/array-ty.hh src/ast/array-ty.hxx src/ast/array-ty.cc \
  src/ast/assign-exp.hh src/ast/assign-exp.hxx src/ast/assign-exp.cc \
  src/ast/ast.hh src/ast/ast.hxx src/ast/ast.cc \
  src/ast/break-exp.hh src/ast/break-exp.hxx src/ast/break-exp.cc \
  src/ast/call-exp.hh src/ast/call-exp.hxx src/ast/call-exp.cc \
  src/ast/cast-exp.hh src/ast/cast-exp.hxx src/ast/cast-exp.cc \
  src/ast/cast-var.hh src/ast/cast-var.hxx src/ast/cast-var.cc \
  src/ast/class-ty.hh src/ast/class-ty.hxx src/ast/class-ty.cc \
  src/ast/dec.hh src/ast/dec.hxx src/ast/dec.cc \
  src/ast/decs-list.hh src/ast/decs-list.hxx src/ast/decs-list.cc \
  src/ast/escapable.hh src/ast/escapable.hxx src/ast/escapable.cc \
  src/ast/exp.hh src/ast/exp.hxx src/ast/exp.cc \
  src/ast/field.hh src/ast/field.hxx src/ast/field.cc \
  src/ast/field-init.hh src/ast/field-init.hxx src/ast/field-init.cc \
  src/ast/field-var.hh src/ast/field-var.hxx src/ast/field-var.cc \
  src/ast/for-exp.hh src/ast/for-exp.hxx src/ast/for-exp.cc \
  src/ast/function-dec.hh src/ast/function-dec.hxx src/ast/function-dec.cc \
  src/ast/if-exp.hh src/ast/if-exp.hxx src/ast/if-exp.cc \
  src/ast/int-exp.hh src/ast/int-exp.hxx src/ast/int-exp.cc \
  src/ast/let-exp.hh src/ast/let-exp.hxx src/ast/let-exp.cc \
  src/ast/method-call-exp.hh src/ast/method-call-exp.hxx src/ast/method-call-exp.cc \
  src/ast/method-dec.hh src/ast/method-dec.hxx src/ast/method-dec.cc \
  src/ast/name-ty.hh src/ast/name-ty.hxx src/ast/name-ty.cc \
  src/ast/nil-exp.hh src/ast/nil-exp.hxx src/ast/nil-exp.cc \
  src/ast/object-exp.hh src/ast/object-exp.hxx src/ast/object-exp.cc \
  src/ast/op-exp.hh src/ast/op-exp.hxx src/ast/op-exp.cc \
  src/ast/record-exp.hh src/ast/record-exp.hxx src/ast/record-exp.cc \
  src/ast/record-ty.hh src/ast/record-ty.hxx src/ast/record-ty.cc \
  src/ast/seq-exp.hh src/ast/seq-exp.hxx src/ast/seq-exp.cc \
  src/ast/simple-var.hh src/ast/simple-var.hxx src/ast/simple-var.cc \
  src/ast/string-exp.hh src/ast/string-exp.hxx src/ast/string-exp.cc \
  src/ast/subscript-var.hh src/ast/subscript-var.hxx src/ast/subscript-var.cc \
  src/ast/ty.hh src/ast/ty.hxx src/ast/ty.cc \
  src/ast/typable.hh src/ast/typable.hxx src/ast/typable.cc \
  src/ast/type-constructor.hh src/ast/type-constructor.hxx src/ast/type-constructor.cc \
  src/ast/type-dec.hh src/ast/type-dec.hxx src/ast/type-dec.cc \
  src/ast/var.hh src/ast/var.hxx src/ast/var.cc \
  src/ast/var-dec.hh src/ast/var-dec.hxx src/ast/var-dec.cc \
  src/ast/while-exp.hh src/ast/while-exp.hxx src/ast/while-exp.cc
